### ISSUE TITLE
Errors during launch are hidden by launch status card

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#1009]
Picture says it better than I can :)

![Screenshot 2019-03-14 at 11 28 39 AM](https://user-images.githubusercontent.com/199891/54369515-753e8080-464c-11e9-995a-050074db2671.png)

**Comment by ia3andy** [comment]
@ALRubinger indeed :-)

You shouldn't have the popup at the same time @edewit can u look, I must have made a mistake in the conditions in `LaunchFlow`

**Comment by ia3andy** [comment]
@edewit when there is an error, you are suppose to stay in Edition mode with the error panel shown
