### ISSUE TITLE
When launching, spinny box comes up but nothing appears to happen

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#1023]
Using Minishift, I get the spinny box:

![screenshot2](https://user-images.githubusercontent.com/199891/54481745-1a08bb80-480f-11e9-95b8-f23203400edd.png)

...but nothing seems to be going on.  Network monitor, cleared right before launch, shows no new activity going outta the browser:

![screenshot3](https://user-images.githubusercontent.com/199891/54481746-1a08bb80-480f-11e9-93a4-3db110620b30.png)

**Comment by quintesse** [comment]
Yeah, got that too. `Cannot read property 'filter' of undefined` in the console.
