### ISSUE TITLE
Hint doesn't make sense with Import flow

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-frontend#1040]
![image](https://user-images.githubusercontent.com/778793/54551926-4b1ff200-49af-11e9-9333-54cb8e208e08.png)

**Comment by edewit** [comment]
What do you suggest @quintesse, to me it's obvious that you need to configure the source repository in order to import

**Comment by quintesse** [comment]
Ah I see now that I read this wrong, probably because of the word "configure" I assumed it was talking about a destination repository. So perhaps just a slight rewording might do. Something like "You should select a repository to import from." perhaps?
