### ISSUE TITLE
Link in header image is broken

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#1043]
This image:

![screenshot2](https://user-images.githubusercontent.com/199891/54568109-6b9a7d00-49ac-11e9-979b-68b3390b773b.png)

...points to:

`http://launcher-launcher.192.168.99.100.nip.io:8080/launch/`.  Correct URL should be `http://launcher-launcher.192.168.99.100.nip.io/`, no?

**Comment by ia3andy** [comment]
@gastaldi an opinion on this? 

I guess for now, we don't really have a choice because of https://developers.redhat.com/launch/
Maybe we could get our own subdomain (like https://launch.developers.redhat.com)?

**Comment by edewit** [comment]
It's fine that it points to `/launch/`, I think what one expects is to see the "intro" screen again, so maybe we need to call logout onclick?

**Comment by ia3andy** [comment]
> so maybe we need to call logout onclick?
@edewit that would be weird 🤔

I guess we could redirect to the "menu" page when you are logged in, it actually does, but for now we have the session storage cache..

IMO the best solution would be to handle the menu with Route:
- /launch/ => menu
- /launch/new-app => ..
- ...

We should make this new routed `launcher` component part of the `launcher-app` so we don't affect the component itself.. I've got an idea on how to deal with that.
