### ISSUE TITLE
Import needs to send two more parameters

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-frontend#1053]
For the import besides the `gitImportUrl` that needs to be passed as part of the descriptor JSON we also need the two `gitRepository` and `gitOrganization` values as for a normal Launch.

For this the `gitImportUrl` will need to be parsed and it's path split like I did here too: https://github.com/fabric8-launcher/launcher-creator-backend/blob/d2eb81b297b8330cf3ff5beb73744070f8a9a5ba/lib/server.ts#L203-L215

It also means the the UI should check that the URL it only to github.com

This is all a temporary hack to get things ready for this train. As soon as the Launcher Backend has proper support we can remove these limitations again.

**Comment by ia3andy** [comment]
@quintesse could we make this hack part of the backend?
