### ISSUE TITLE
Broken link after deploy of "Create New"

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#1055]
This link, after deploying:

![screenshot1](https://user-images.githubusercontent.com/199891/54618566-9d0d5a00-4a39-11e9-88d6-57a5795df01b.png)

...points to: `https://github.com/ALRubinger/react-quarkus-mysql/blob/master/README.adoc`.

Should be: `https://github.com/ALRubinger/react-quarkus-mysql/blob/master/README.md`

(Note "md" instead of "adoc" in this case).

**Comment by quintesse** [comment]
For now the easiest solution is just to assume that created apps always use `README.md`.

Also, it has to be removed for the import flow because it might not even have a README but even if it does it's unlikely to be very helpful.

**Comment by edewit** [comment]
Let's remove this link entirely the link to the repo also shows the README regardless if it's using `.adoc` or `.md`

**Comment by ALRubinger** [comment]
@edewit Brilliant.
