### ISSUE TITLE
Link to Welcome app?

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1063]
Where is the Welcome app link after launch? We used to have that in the original UI

![Screenshot from 2019-03-19 23-54-02](https://user-images.githubusercontent.com/54133/54655886-4c7e1700-4aa2-11e9-83ae-c76b33b316ab.png)

**Comment by ALRubinger** [comment]
Great catch!

**Comment by edewit** [comment]
It's only there if the backend returns it, let me investigate
