### ISSUE TITLE
Logout link does not logout from KeyCloak

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1077]
It redirects to the initial page but it doesn't prompt me for my credentials

**Comment by ia3andy** [comment]
@gastaldi this is because of this: https://github.com/fabric8-launcher/launcher-frontend/issues/1047

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-frontend/commit/cf222bec6fd68f3df73aebbb20184700e4890ed7
