### ISSUE TITLE
Blank screen bug

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-frontend#1083]
I got something weird. I'm logged in with my account so when I go to https://launch.prod-preview.openshift.io I get the 3 cards that ask for what I want to do. So I click on Create New and I get to the page (which is half-filled from a previous session I started). I see a spinner in the OpenShift box and the moment that stops the entire page become blank.

This is what I see in the browser console:

```
GLOBAL_CONFIG is: {"launcherApiUrl":"https://forge.api.prod-preview.openshift.io/api","creatorApiUrl":"https://forge.api.prod-preview.openshift.io/creator","keycloakUrl":"https://sso.openshift.io/auth","keycloakRealm":"rh-developers-launch","keycloakClientId":"","segmentTrackerToken":"dMV5AjaweCpO3KZop7TuZ0961UO74AF0","sentryDsn":"https://12813ed59a0546eaaf068d90127044c9@errortracking.prod-preview.openshift.io/29?environment=prod-preview","targetEnvironmentSkip":""}
keycloak.js:448 [KEYCLOAK] Refreshing token: forced refresh
keycloak.js:478 [KEYCLOAK] Token refreshed
keycloak.js:827 [KEYCLOAK] Estimated time difference between browser and server is 0 seconds
keycloak.js:831 [KEYCLOAK] Token expires in 900 s
react-dom.production.min.js:4408 TypeError: Cannot read property 'name' of undefined
    at Object.children (index.js:1900)
    at $t (index.js:601)
    at Qo (react-dom.production.min.js:3273)
    at Ba (react-dom.production.min.js:3745)
    at Da (react-dom.production.min.js:3957)
    at Vi (react-dom.production.min.js:5514)
    at $i (react-dom.production.min.js:5536)
    at Su (react-dom.production.min.js:5958)
    at Bu (react-dom.production.min.js:5925)
    at Eu (react-dom.production.min.js:5860)

```

**Comment by quintesse** [comment]
If I do Clear Storage from the browser's dev console things start working again.

**Comment by edewit** [comment]
the problem is stacktraces from staging are pretty useless, because the code is minified. Can we temporarily not do that @ia3andy ?

**Comment by quintesse** [comment]
The problem is more that I don't know how to reproduce the issue ;-)
I´m _guessing_ there was something wrong with the information stored in the session. Perhaps it would be a good idea to validate it first and clear the storage if anything is found wrong with it. Or clear it in the case of any exceptions being throws in the code.

**Comment by ia3andy** [comment]
This must be due to a change of model in the app (in between the loads), this shouldn't happen very often. Logout/Cancel should be clearing it. We now have sentry enable, if we see it happens more than expected, we'll find a fix..
