### ISSUE TITLE
Project name?

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1084]
How do I specify the project name to be used in OpenShift? I know it takes from the Github repository, but I'd like to deploy to an existing project

**Comment by ia3andy** [comment]
@gastaldi I knowingly ignore this matter for the first release.
We will need a way to select it and also the special runtime conf (like artifactId...).
I guess this will be easier to integrate after we have solved this issue: https://github.com/fabric8-launcher/launcher-frontend/issues/903

**Comment by ia3andy** [comment]
#1122 and #1123
