### ISSUE TITLE
Launch button posts to the wrong URL, giving 404

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1089]
Tested in the Create Flow (Angular JS + Nodejs backend). When the launch button is clicked a 404 appears.

The URL is POSTing to `/api/launch`, when it should be `/api/launcher/launch`

![Screenshot from 2019-03-21 11-28-12](https://user-images.githubusercontent.com/54133/54759350-aa0e8280-4bcc-11e9-9ae8-b96cea04a30f.png)

**Comment by ia3andy** [comment]
Closed by https://github.com/fabric8-launcher/launcher-frontend/commit/73759ae21b030facde42e9d16ab751eaad162ad6

The configmap has been auto deleted leading to using the default value which was wrong..
