### ISSUE TITLE
Improve client to give statusCode in case of error

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#1100]
Use it to make github authorization more consistant

**Comment by ia3andy** [comment]
@edewit #1136  was only the first part of this issue. Second part is to use the status code for github 404 handling.

**Comment by edewit** [comment]
this issue states "Improve client to give statusCode in case of error", but I could add that to the fix as well.

**Comment by ia3andy** [comment]
and the description: "Use it to make github authorization more consistant" 😁Ok I should have created two issues lol, let me create another one: #1143
