### ISSUE TITLE
Allow user to select project name

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#1122]

**Comment by gastaldi** [comment]
@ia3andy is this issue going to make it to Summit? I'd prefer to bump to the Train M instead, unless you have any objections, of course :)

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/56645092-4c62cf80-667d-11e9-9089-fd01b80dac0b.png)

As decided with @edewit "Project Name" input will be a text input next to the title (like it was in the angular wizard).

The flow:
- if project name is updated and git repository name is still default, then we change it with the user selection
- same if the user change the git repository name..

**Comment by quintesse** [comment]
> if project name is updated and git repository name is still default, then we change it with the user selection
> same if the user change the git repository name..

Those can't both be true, right? 
I mean, you could never give them different values :-)

I'd suggest we only keep the first rule?

**Comment by ia3andy** [comment]
@quintesse  I guess you've got it wrong. The second rule is that if the user change the git repository name and the project name is still default, then we update it. Which means you can freely change both:
Example 1:
- Change project name in main screen, repository name is updated
- Change name of the repository, project name is not updated

Example 2:
- Change repository name, project name is updated
- Change project name, repository name is not updated

**Comment by ia3andy** [comment]
@quintesse next time, I'll not be lazy in the rule definition haha 😅

**Comment by quintesse** [comment]
Isn't that weird?

So you're saying that:

 - The default was set to "Foo", both values are "Foo"
 - Now the user changes the project name to "Bar, Git repo gets updated to "Bar" too, both values are "Bar"
 - But if the user now goes to the repo and changes "Bar" to "Baz"  the project name does not update?

But if the user changes the repo first the project name _does_ update?

Also what happens if the user changes the value twice?

This seems somewhat confusing TBH

**Comment by quintesse** [comment]
Also what if I like the generated project name but just want to change the repo name? I can't do that, right? I _must_ change the project name first or change it back later.

**Comment by ia3andy** [comment]
This rule is just to help the user to **change the default value** quickly but it does not affect after changing it. To me it makes sense @edewit what your opinion?

**Comment by ia3andy** [comment]
This is not easy to make, so if you feel it's not a good thing, let's just don't do it..

**Comment by quintesse** [comment]
If it's difficult I'd just do it without the auto-updating. I think it might be hard to find something that will be clear and non-confusing for everybody.

**Comment by ia3andy** [comment]
@quintesse you are right.

Let’s make this version where project name and repository name are not connected at all.
The only "link" is that they use the same default value.

If we feel that it needs a connection at use, we'll do it in another version.

Thanks for the advices..

**Comment by quintesse** [comment]
Yeah, you're absolutely right. Let's not waste time on this right now :-)
