### ISSUE TITLE
Configure CI to release launcher-client on npm and components on storybook

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#1124]

**Comment by gastaldi** [comment]
How is this going to work? Should the release use launcher-frontend with the `semantic-release` plugin or should that happen package-level?

**Comment by ia3andy** [comment]
@gastaldi I have no idea yet :-) I need to dig, I think `lerna` is nice for those cases..

**Comment by edewit** [comment]
fixed in 283728693ce7834e53b94184adacc17bbd8cbe72
