### ISSUE TITLE
Maven Artifact not being set after redirect back from Github Auth

### ISSUE THREAD

**Issue by david-martin** [fabric8-launcher/launcher-frontend#1126]
launcher-frontend version: 7b1c127 (old ui)

We're seeing an issue where the `Maven Artifact` field doesn't get set the first time after the user authorizes their Github account.
![image](https://user-images.githubusercontent.com/878251/54914052-04208800-4eec-11e9-9e9d-078d8553be9a.png)

It looks like the `updateArtifactInfo` only gets called when booster or runtime is changed.
https://github.com/fabric8-launcher/ngx-launcher/blob/26c29a76f697a3d212d80ece75884f170cce1d98/projects/ngx-launcher/src/lib/components/targetenvironment-step/target-environment-step.component.ts#L72-L94
However, when redirected from Github, the state is restored based on query params, and `updateArtifactInfo` isn't triggered.

I've shown this issue to @edewit to ensure this is actually a frontend issue and not something silly I'm doing. (Thanks @edewit).

As we're using a commit for the old ui, this may require a maintenance release/branch/tag as we (Integreatly) are not in a state to update to the latest ui yet.

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-frontend/commit/31c95532c642c6f4d74ad260dcedb9e8fc67cd7d
