### ISSUE TITLE
Make sure that all compatible examples can be launched

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#1138]
For now we block "launch" on some example because they may fail on the target cluster. We need to make sure it is the case to so we don't miss any example for a wrong reason.

**Comment by quintesse** [comment]
From @ALRubinger : 

> * Allow Istio stuff to show up in local for Launch
> * Explicitly designate that these examples require Istio support enabled in that cluster
> It's just about setting expectations for users and avoiding failures where success is expected

So I'd say we should just show them (they will only show up for people running Minishift anyway, so they are already using a non-trivial setup so we can expect them to be somewhat more knowledgeable) with some kind of "Needs ISTIO configured on target cluster" warning.

**Comment by quintesse** [comment]
The missions are already tagged with `istio: true` so it should be easy to display that warning: https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/metadata.yaml#L62

**Comment by quintesse** [comment]
A better solution might be that clusters that have ISTIO installed are marked that way, but of course that would mean manually maintaining that flag in the cluster list.

An even better way would be to detect ISTIO being installed on the cluster, but who knows if that's even possible.

**Comment by edewit** [comment]
releated to: #1054

**Comment by ia3andy** [comment]
I guess it's fixed
