### ISSUE TITLE
Example can't be downloaded

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-frontend#1230]
## Issue

An example can't be downloaded after we have selected `Spring Boot` runtime, `REST example`

![Screenshot 2019-04-10 09 53 40](https://user-images.githubusercontent.com/463790/55861696-2f0b0d00-5b77-11e9-8ce4-a620ea832f38.png)

## Steps

```
go get github.com/fabric8-launcher/launcher-operator
cd ~/Code/go-workspace/src/github.com/fabric8-launcher/launcher-operator
minishift start
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc login -u admin -p admin
oc create -R -f ./deploy
oc create secret generic launcher-secrets --from-literal=github-token=launcher
secret/launcher-secrets created
oc create -f example/launcher_cr.yaml
```

Next

```
open the launcher application within the browser
Select `Deploy an Example Application`
Select `An Example`
Click on `REST API Level 0`
Select Spring Boot and version 2.1.3
Click on the Save button
Click on Download button
```

**Comment by cmoulliard** [comment]
I think that we have different issues as this error is reported when we open the first time the launcher

![Screenshot 2019-04-10 10 04 03](https://user-images.githubusercontent.com/463790/55862077-06cfde00-5b78-11e9-94cd-9816a836a5e3.png)

and this one occurs when we click on the `Download` button

![Screenshot 2019-04-10 10 05 07](https://user-images.githubusercontent.com/463790/55862143-28c96080-5b78-11e9-8356-9c757d5ecea6.png)

**Comment by cmoulliard** [comment]
why do we get such error within the Browser UI -> `Failed to load resource: the server responded with a status of 401 (Unauthorized)` ?

**Comment by ia3andy** [comment]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/13069/
