### ISSUE TITLE
Add new frontend openshift config parameters to configure openshift auth

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#1237]
Once this PR #1231 is merged, we will need new config parameters in the openshift template to configure it, and update the operator to handle it.

**Comment by gastaldi** [comment]
@ia3andy the OAuth URL is being sent as part of the `/api/services/openshift/clusters` JSON: https://github.com/fabric8-launcher/launcher-backend/pull/744#issue-270670682. I think it's worth using it instead of being set separately, WDYT?

**Comment by ia3andy** [comment]
@gastaldi for now at least, we don't need it because the login use the oauth url really early in the flow.

In the future, I guess the user should be able to access the launcher without login. Then it may be important to have oauth for the different clusters => https://github.com/fabric8-launcher/launcher-frontend/issues/1254
