### ISSUE TITLE
projectName is not sent when downloading Node.js Example ZIP

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1253]
See https://issues.jboss.org/browse/LAUNCHER-27 for details on how to reproduce it.

The resulting URL is https://forge.api.openshift.io/api/launcher/zip?groupId=com.yourcompany.newapp&artifactId=gifted-baseball&projectVersion=1.0.0&targetEnvironment=os&mission=health-check&runtime=nodejs&runtimeVersion=v10-redhat, which is missing the required projectName parameter

**Comment by gastaldi** [comment]
@fabric8-launcher/frontend-devs anyone can have a look at this?

**Comment by gastaldi** [comment]
I have pushed a fix in the backend that will ignore the projectName parameter if the frontend doesn't send it

**Comment by ia3andy** [comment]
@gastaldi I thought `projectName` wa used only for openshift.. what is it used for for download?

**Comment by gastaldi** [comment]
@ia3andy see https://editor.swagger.io/?url=https://forge.api.openshift.io/openapi 

It is used as the ZIP file name and in Node.js project name
