### ISSUE TITLE
Allow user to select the project name in the Import flow

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1276]

**Comment by ia3andy** [comment]
@gastaldi is this necessary? We auto-define the project name from the git imported repo

**Comment by gastaldi** [comment]
@ia3andy sometimes the git imported repo name is already used in another project in the same cluster and the user doesn't have permission to deploy to it. 

In another words, it is correct to auto-define the project name based on the git imported repo name but it would be awesome if we could change that

**Comment by gastaldi** [comment]
Also since the Import flow is in Beta, we can bump this to Train M

**Comment by ALRubinger** [comment]
Use case: generate new app in creator.  Go to import.  Because you cannot change the name on import, there are name clashes and failure.  Prioritizing to current Summit train.
