### ISSUE TITLE
Add external link to OpenShift console in the OpenShift Deployment card

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#1277]
It would be nice if the chosen OpenShift cluster name were a link that would open the console URL (if that is available, since the consoleUrl is an optional attribute) 

![image](https://user-images.githubusercontent.com/54133/56825882-f040ac80-6830-11e9-9291-1fea2a33c6d6.png)

**Comment by edewit** [comment]
@gastaldi would be nice if it was a [documented property](https://github.com/fabric8-launcher/launcher-backend/blob/master/web/src/main/resources/META-INF/openapi.yml) as well
