### ISSUE TITLE
Failure to Create Project on Openshift Online When Project Name Starts with 'openshift-'

### ISSUE THREAD

**Issue by darahayes** [fabric8-launcher/launcher-frontend#210]
Hey there, 

I've just tried the launch.openshift.io wizard. It's an amazing piece of work! 🎉 However, I did run into an issue while launching my application.

Here are some of the details:

- runtime: Node.js
- project name/github repo: `openshift-launch-node`
- Mission type: Config Maps

And I got the following error:

<img width="1540" alt="screen shot 2017-11-14 at 12 38 44" src="https://user-images.githubusercontent.com/8656188/32780682-180c1584-c93a-11e7-93b4-0e887e0b4be1.png">

I only have a basic level of Kubernetes/Openshift experience but my guess would be that Openshift doesn't like when a user creates a project that has a name prefixed with `openshift-`

If that is indeed desired behaviour, then the fix for this in `launchpad-frontend` might be a simple check in the form validation for the project/repo names.

Thanks for your time!

**Comment by edewit** [comment]
thanks for you issue, this will be fix in the next release where we automatically prefix the project name with your username
