### ISSUE TITLE
Error with no context if associating RHT account with GitHub account already associated with a different RHT account

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#223]
When going to associate my GitHub account:

![screenshot1](https://user-images.githubusercontent.com/199891/35492563-a32ae592-047b-11e8-8879-7a74089dc75a.png)

...I get this error:

![screenshot2](https://user-images.githubusercontent.com/199891/35492569-ac40e5dc-047b-11e8-88aa-f9af4ea0f848.png)

Doing it manually via https://sso.openshift.io/auth/realms/rh-developers-launch/account/identity I see the reason:

![screenshot3](https://user-images.githubusercontent.com/199891/35492581-ba49ba28-047b-11e8-9f22-94bc1586c45d.png)

We need to provide some better context to the user in this case

**Comment by gastaldi** [comment]
Perhaps we could redirect the user to the Keycloak page and apply some CSS sytling to make it look like our page

**Comment by edewit** [comment]
Don't think that is an option, also due to security. I think the best option is to move this functionality to the backend similarly as OSIO has done maybe?
