### ISSUE TITLE
Create a cico_run_tests.sh script to be executed by the CI server

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#229]
This script will be executed when a PR is provided to this repository.

Examples: 
- https://github.com/fabric8-ui/fabric8-ui/blob/master/cico_run_tests.sh
- https://github.com/fabric8-launcher/launcher-backend/blob/master/cico_run_tests.sh

**Comment by quintesse** [comment]
There's already a `cico_build_deploy.sh` there, would it be very similar to that?

**Comment by edewit** [comment]
fixed in 34cfaebfc2d24150a5ef49aa90e7b2898d6ce380
