### ISSUE TITLE
Last button in the openshift flow

### ISSUE THREAD

**Issue by edewit** [fabric8-launcher/launcher-frontend#303]
Last button in the openshift flow needs to present the user with some next steps that he can take. Instead of going back to the start / front page.

**Comment by gastaldi** [comment]
How does that work now? Is it a static text?

**Comment by edewit** [comment]
in the new almost everything is just static text

**Comment by gastaldi** [comment]
I like the old "after launch" page, can we keep that?

**Comment by ia3andy** [comment]
do you guys means having those screens in the new wizard?
<img width="895" alt="capture d ecran 2018-04-25 a 18 30 24" src="https://user-images.githubusercontent.com/2223984/39259479-c9a4a3d2-48b6-11e8-8095-995b8c01d8b4.png">

<img width="835" alt="capture d ecran 2018-04-25 a 18 28 39" src="https://user-images.githubusercontent.com/2223984/39259388-960e1184-48b6-11e8-888b-e9309256a46a.png">

**Comment by edewit** [comment]
@ia3andy next step for zip is already there the other is missing
