### ISSUE TITLE
Add a Provide Feedback option 

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#325]
This request comes from @burrsutter:

> we should have a "provide feedback" option visible in launch.openshift.io so that it is easy for a user to say "hey, I am trying X and it does not work quite right".

**Comment by gastaldi** [comment]
Ideally it would be nice to use the Sentry User Feedback dialog, since we are integrated with it for error reports (Sentry also allows creating Github issues from the UI): 

https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/settings/user-feedback/

**Comment by ia3andy** [comment]
> Ideally it would be nice to use the Sentry User Feedback dialog, since we are integrated with it for error reports (Sentry also allows creating Github issues from the UI):

@gastaldi I think this is only to add feedback when a specific error did occur.

**Comment by gastaldi** [comment]
>@gastaldi I think this is only to add feedback when a specific error did occur.

@ia3andy right, I think that's when someone wishes to provide feedback, no? :smile: 
I think we could start with something like that for now.

**Comment by ia3andy** [comment]
>  I think that's when someone wishes to provide feedback, no?

Lol :) I was thinking about feedback as ideas or suggestions for example..

> I think we could start with something like that for now.

I will look into that ;)

**Comment by gastaldi** [comment]
> I was thinking about feedback as ideas or suggestions for example..

Sure, I think that would be nice to have too. Maybe we could point to the launcher-planning repository and ask them to create an issue there or something like that.

**Comment by gastaldi** [comment]
Using Sentry requires resolving https://github.com/fabric8-launcher/launcher-frontend/issues/327 first
