### ISSUE TITLE
Unable to run fabric8 launcher in minishift 

### ISSUE THREAD

**Issue by petenorth** [fabric8-launcher/launcher-frontend#360]
I am running 

minishift v1.15.1+f19ac09
CDK v3.4.0-2

openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657

and am attempting to work through 

https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/install_and_configure_the_fabric8_launcher_tool/#introduction-to-the-launcher-application

The backend seems to OK (it manages to clone everything and doesn't log any errors) but the front has the following problems (screenshot from the browser console in Chrome). I had to make one change for the frontend to deploy successfully in the cluster configmap (I added a blank entry for `launcher.keycloak.clientId` otherwise the it wouldn't start and I got a configuration error).

It seems that 

launcher.frontend.sentry.dsn | ${LAUNCHER_FRONTEND_SENTRY_DSN}

Is a problem?

![screenshot from 2018-05-18 10-45-03](https://user-images.githubusercontent.com/3152937/40228248-a976c476-5a88-11e8-812a-124c92d84f73.png)

**Comment by ia3andy** [comment]
Thank you for letting us know about this issue @petenorth.

I have found the problem, it should be fixed soon. I will keep you updated.

Sorry again..

**Comment by ia3andy** [comment]
@petenorth it should be ok now :)

Don't hesitate to reopen the issue if the fix didn't solve the problem for you.

**Comment by petenorth** [comment]
@ia3andy Yes, created a clean project and did a clean install and everything works fine. Managed to create both a 'build and run locally' and a 'Use Openshift' style project with the latter successfully building etc.

Thanks for the quick fix.
