### ISSUE TITLE
Cluster unavailable missions take too much space

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#390]
![image](https://user-images.githubusercontent.com/2223984/40834333-cd7fcba2-6590-11e8-9828-f5940f28dd3d.png)

We could "single line" them showing just the title, "more" and the ribbon.
And put them at the bottom since they won't change in the step (they will change only if you change the cluster)

**Comment by gastaldi** [comment]
@bdellasc any thoughts about these? @ia3andy can you paste the proposed change in this issue? Thanks!

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/42167750-40d5f4dc-7e0f-11e8-87a7-48455e65dd70.png)
