### ISSUE TITLE
Missions and Runtimes are disabled when Zip Download is chosen

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#395]
Steps to reproduce:

- Choose to deploy on Openshift and pick a starter cluster
- Click on any enabled mission (some of them are disabled)
- Go back to the previous step
- Choose to download ZIP
- There are Missions and Runtimes still disabled. They should all be available

**Comment by ia3andy** [comment]
this will be fixed by 
https://github.com/fabric8-launcher/ngx-launcher/pull/256
