### ISSUE TITLE
Github Authorization not working

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launcher/launcher-frontend#488]
ATM, on https://launch.prod-preview.openshift.io/launch/, github authorization is not working. When clicking _Log In & Authorize Account_, it does not allow me to go forward.

**Comment by gastaldi** [comment]
@edewit @ia3andy any idea?

**Comment by rhoads-zach** [comment]
This is also broken in minishift.

To reproduce:
1. Install using: https://launcher-preview.fabric8.io/docs/minishift-installation.html#installing-launcher-tool_minishift
2. Create a booster using the GH flow
3. Notice it prompts you to authorize when it should already be connected to GH.
4. If you attempt to authorize, it redirects you to the start page

If you use the `v20` version of the template, everything is fine.

**Comment by gastaldi** [comment]
@edewit this is the commit that broke it: 135828011a25f97799e734003729d4b4c2bcf21c. I am reverting it now

**Comment by rhoads-zach** [comment]
thank you @gastaldi, LGTM
