### ISSUE TITLE
Ask for credentials on the last step of provisioning

### ISSUE THREAD

**Issue by mickaelistria** [fabric8-launcher/launcher-frontend#503]
Currently, the credentials are requested very early. It may drive people away too fast. As an alternative, it would be more interesting to get people filling the various forms, seeing the various options, and ask for their credentials when actually creating the project and not earlier.

**Comment by gastaldi** [comment]
The RH Developers login when entering the first screen is a requirement from PM / BU. I see why that may be annoying,  but the majority of the services also require authentication to work properly, so we'd have to check if using Launcher without being authenticated is a valid option.

**Comment by mickaelistria** [comment]
Ok, no problem. Usually, delaying the login screen just before providing the value (in this case generating the project) leads to a much higher "transformation rate" which is probably desired by the PM/BU. I remember there's a UX website that shows some UX practices and measures their impact on users. I'll try to find the link later and share it with you so you'll be able to show PM that it's a profitable idea for everyone.

**Comment by mickaelistria** [comment]
See https://goodui.org/#22 on this topic.

**Comment by ia3andy** [comment]
@gastaldi what should we do with this matter?

**Comment by gastaldi** [comment]
@ia3andy that looks like an interesting enhancement. Maybe the cards that require authentication could show a message (`You need to be authenticated`) and when the user clicked the button to open the card it would redirect to the login page first. WDYT?

**Comment by ia3andy** [comment]
Closing in favor of (which is really similar): https://github.com/fabric8-launcher/launcher-frontend/issues/1254
