### ISSUE TITLE
typo README.doca instead of README.adoc

### ISSUE THREAD

**Issue by apupier** [fabric8-launcher/launcher-frontend#592]
![image](https://user-images.githubusercontent.com/1105127/42512458-f30d2544-8454-11e8-8cd4-b0cd43a6416b.png)

i was pointed to this github repository to fix it but a search in github provides no result for this typo, please redirect if needed

**Comment by gastaldi** [comment]
This issue was moved to fabric8-launcher/ngx-launcher#325
