### ISSUE TITLE
Design suggestion for cluster selection

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#662]
![image](https://user-images.githubusercontent.com/2223984/44531936-39fd5400-a6f2-11e8-9d65-a98f2f1b0a28.png)

**Comment by ia3andy** [comment]
Selection is visible only when openshift is select as Target Env

**Comment by ia3andy** [comment]
@edewit @quintesse @gastaldi wdyt?

**Comment by edewit** [comment]
:+1: I like it

**Comment by quintesse** [comment]
Not sure I understand?

**Comment by ia3andy** [comment]
@quintesse before..
![image](https://user-images.githubusercontent.com/2223984/44575610-a9278680-a78c-11e8-8c8b-4da799c861df.png)
