### ISSUE TITLE
Lack of token refresh leads to invalidation due to timeout in the backend

### ISSUE THREAD

**Issue by bartoszmajsak** [fabric8-launcher/launcher-frontend#744]
Launcher Backend [validates JWT](https://github.com/fabric8-launcher/launcher-backend/pull/557) right now. We are facing token timeout errors coming from Standalone Launcher which is validated against KC. It seems that lifespan of those tokens is set to 5 minutes, 

![image](https://user-images.githubusercontent.com/719616/47593876-c4da1500-d914-11e8-8755-aff076b4529b.png)

which might be the reason of problems observed in Sentry - two events correlating to the same request can be found here [[1](https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/9121/)] [[2](https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/9120/)].

We should refresh tokens before they expire in the front-end, otherwise, this might be quite a common scenario.

**Comment by alexeykazakov** [comment]
You could use Keycloak Javascript adapter for that.

**Comment by edewit** [comment]
we use this:
https://github.com/fabric8-launcher/launcher-frontend/blob/master/src/app/shared/keycloak.auth.service.ts#L74
