### ISSUE TITLE
Spinney Loading on Home Page Takes Way Too Long

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-frontend#772]
![screenshot2](https://user-images.githubusercontent.com/199891/49097330-88af1280-f23a-11e8-8473-e046dd1d0862.png)

Thoughts on this?  Should we kill the landing page alltogether and simply start people off on the screen asking them whether they want to launch an "Example" or "Create New Application?"

**Comment by edewit** [comment]
This is shown when angular is starting, removing the landing page will not improve this. We can have a look at optimizing this though.

**Comment by ia3andy** [comment]
Closed because a new react based frontend is now available.
