### ISSUE TITLE
Thorntail runtime description overflows its panel

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#808]
It seems to be a screen resolution problem, mine is 1920x1080

![screenshot from 2018-12-10 11-49-52](https://user-images.githubusercontent.com/54133/49736814-4641f880-fc72-11e8-8f15-ec09e5aa118c.png)

**Comment by edewit** [comment]
that will introduce more problems the UI has been designed to maximum 1440 x 1080
