### ISSUE TITLE
Store form state for the user to avoid having to restart on reload  

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#915]
I guess we should use the session storage for this. We could look  for an existing hook or at least get inspiration there:
https://github.com/rehooks/awesome-react-hooks

something like `useSessionStoredState` would be perfect.

**Comment by edewit** [comment]
There is already this: https://www.npmjs.com/package/react-use-localstorage

**Comment by edewit** [comment]
and now there is https://www.npmjs.com/package/react-use-sessionstorage
