### ISSUE TITLE
Import should allow for more flexible input

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-frontend#942]
Right now the import only allows you to select repositories that are already yours, you should of course be able to select _any_ repository.

I think we should just simply allow the user to enter (copy&paste) a full URL to any Git repository (then we don't need to worry about GitHub vs GitLab vs BitBucket either)

**Comment by ia3andy** [comment]
@quintesse indeed this will be way simpler :-) 

I guess @edewit thought it would be the same as the existing OSIO import flow logic when he made it this way...

**Comment by ia3andy** [comment]
Closed by https://github.com/fabric8-launcher/launcher-frontend/commit/264be7a4c367e2fbe21ce44e7bb03c3fd634f623
