### ISSUE TITLE
Improve Example Picker XP

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-frontend#985]
Old version:
![image](https://user-images.githubusercontent.com/2223984/54141632-59599580-4426-11e9-8c28-e418c8abf423.png)

My opinion is that is too complex.

Subject to discussion by @edewit @quintesse @ALRubinger @gastaldi

**Comment by edewit** [comment]
Added the "Already decided" runtime filter, but it works a lot simpler then in the old version. It will filter the mission list to all missions that are available for that runtime and dropdowns for the runtime will be pre-selected with the runtime that the user is filtering on.
