### ISSUE TITLE
JWT token must be always sent

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-frontend#986]
The JWT token must be always sent in the secured services (containing a lock), even if Keycloak is not enabled: https://editor.swagger.io/?url=https://forge.api.prod-preview.openshift.io/openapi

**Comment by ia3andy** [comment]
Should be done already:
https://github.com/fabric8-launcher/launcher-frontend/commit/6e69b9190ba7f5c5b38a30b4f9eac11618c7fd33
